<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use DB;

class CandidatosInscritos extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $table = 'candidatosinscritos';
    protected $fillable = [
    'idCandidatoInscrito',
	'CursosGrad_idCurso',
	'Cargos_idCargo',
	'Nome',
	'Sexo',
	'RG',
	'OrgaoEmissor',
	'EstadoEmissor',
	'CPF',
	'Naturalidade',
	'DataNascimento',
	'NumConsEdFisica',
	'Telefone1',
	'Telefone2',
	'Logradouro',
	'Bairro',
	'Cidade',
	'Estado',
	'Cep',
	'Email',
	'PossuiVinculoEmpregaticioAtual',
	'CargaVinculoAtual',
	'TurnoVinculoAtual',
	'TipoVinculo',
	'DisponibilidadeInicio',
	'TextoInteresse',
	'DataUltimaAlteracao',
    'idUsuarioUltimaAlteracao',
	'Situacao',
	'motivoDescGrad',
	'token',
	'PossuiDeficiencia',
	'DataInscricao',
	'Raca',
	'urlDoc',
	'DescricaoDeficiencia',
	'Cotista',
	'LaudoUrl',
	'contratadoRegimeEspecial',
	'declaracaoRaca',
	'NumeroInscricao',
	'RejeitarLaudo',
	'RecursoGrad',
	'encaminhado',
	'idMotivoDesclassifica',
	'NumeroHabilitacao',
	'DataEmissaoHabilitacao',
	'CertificadoUrl',
	'NumeroBoleto',
	'Ip',
	'RejeitarCotista',
	'RejeitarCertificado',
	'RetornoBoleto',
	'TipoAnaliseCotista',
	'TipoAnaliseDeficiente',
	'MotivoRejeicaoCotista',
	'MotivoRejeicaoDeficiente',
	'TipoAnaliseCertificado',
	'MotivoRejeicaoCertificado',
	'DataHabilitacaoLancada',
	'NumeroRQ',
	'SituacaoRecurso',
	'JulgaComissaoCotista',
	'posicao_geral',
	'posicao_afro',
	'posicao_pcd',
	'NrConvoca',
	'ListaConvoca',
	'DataConvoca',
	'Historico_Geral',
	'Historico_Afro',
	'Historico_PCD',
	'InstituicaoGraduacao',
	'MesConc',
	'AnoConc',
	'Obs_Recursos',
	'NomeSocial',
	'idCircuito',
	'filiacao',
	'dataEmissor',
	'mae',
	'pai',
	'txtReqRec',
	'txtCursoRec',
	'txtExpRec',
	'txtLaudoRec',
	'txtPPPRec',
	'recursoEnviado',
	'recursoEnviadoPPP',
	'NumeroDAM'
    ];
}
